title: Jiaxin Li # your name (or website title) here
logo: "/images/a00.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  lijx3643@outlook.com 
  <br><br>
  Focus: Data Science & Data Analysis
  <br><br>
  <a href="/images/a00.jpg" download> Download my Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
