title: Jiaxin Li # your name (or website title) here
logo: "/images/a00.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  lijx3643@outlook.com 
  <br><br>
  Focus: Data Science & Data Analysis
  <br><br>
  <a href="./pdf/Resume-JiaxinLi-DS.pdf" download> Download my Resume</a>
  <br><br>
  Performing sophisticated models do yield excellent results, and that is what we keep pursuing all the time, 
  but the more crucial point is how do those data make sense to real life cases.

  
#theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
